!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  blue_h: 122
  blue_s: 247
  blue_v: 125
  expected_sphero_radius: 18
  fwd_hue_max: 255
  fwd_hue_min: 0
  fwd_sat_max: 255
  fwd_sat_min: 0
  fwd_val_max: 255
  fwd_val_min: 220
  green_h: 130
  green_s: 212
  green_v: 125
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      blue_h: 122
      blue_s: 247
      blue_v: 125
      expected_sphero_radius: 18
      fwd_hue_max: 255
      fwd_hue_min: 0
      fwd_sat_max: 255
      fwd_sat_min: 0
      fwd_val_max: 255
      fwd_val_min: 220
      green_h: 130
      green_s: 212
      green_v: 125
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hue_max: 10
      hue_min: 10
      id: 0
      max_contour_area: 750
      min_contour_area: 100
      name: Default
      orientation_covariance: 0.1
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      position_covariance: 3.0
      red_h: 144
      red_s: 212
      red_v: 118
      sat_max: 10
      sat_min: 10
      state: true
      type: ''
      val_max: 255
      val_min: 255
    state: []
  hue_max: 10
  hue_min: 10
  max_contour_area: 750
  min_contour_area: 100
  orientation_covariance: 0.1
  position_covariance: 3.0
  red_h: 144
  red_s: 212
  red_v: 118
  sat_max: 10
  sat_min: 10
  val_max: 255
  val_min: 255
state: []
